<pre class='metadata'>
Title: JavaScript API for Device Bound Session Credentials
Shortname: DBSC JS API
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/dbsc-js-api
URL: https://explainers-by-googlers.github.io/dbsc-js-api
Editor: Sidney Bovet, Google https://google.com, sbovet@google.com
Abstract: An API for client-side DBSC Session State Management.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href=[REPOSITORYURL]>explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
